### ISSUE TITLE
Site Color Scheme

### ISSUE THREAD

**Issue by BrantBart** [BrantBart/Handcrafted-Haven-Group-9#4]
Decide on Colors for Text, Backgrounds, Buttons, Header and Footer, etc.

**Comment by HottieHotton** [comment]
We will utilize [Tailwind](https://v2.tailwindcss.com/docs) for our CSS

**Comment by HottieHotton** [comment]
For basic overview theme, we will also get our frame from [Coolors.co](https://coolors.co/)

**Comment by HottieHotton** [comment]
Currently debating between the following:

https://coolors.co/001412-008f88-c0dfa1-3f6634-0a330f

https://coolors.co/ffffff-86deb7-63b995-50723c-423e28
